### PR TITLE
[ BB2-1152 ] Replace code to utilize the BB2 Python SDK

### PR DESCRIPTION
**Pull request by dtisza1**
**JIRA Ticket:**
[BB2-1152](https://jira.cms.gov/browse/BB2-1152)

**User Story or Bug Summary:**

This installs and uses the python SDK in the sample app code.

There is a corresponding PR in the SDK repo related to changes made while working on this task. See [SDK PR here](https://github.com/CMSgov/cms-bb2-python-sdk/pull/7)

NOTE: See how to test section below!

### What Does This PR Do?

**The following is a summary of the files in this PR**

* Update run.py for reload to work for changes in docker server container.

* Update `Dockerfile` to use cms_bluebutton wheel package file after it is copied in to the `server/` directory.

* Update `get_auth_url()` view to utilize SDK `generate_authorize_url()` method in views.py 

* Create `get_bluebutton_sdk_config_from_request()` util function
  to return SDK config from sample app config and request params in views.py

* Update `get_auth_url()` view to utilize SDK `generate_auth_data()`
  and `generate_authorization_url()` methods in views.py

* Update `authorization_callback()` view to utilize SDK
  `get_authorization_token()` method in views.py

* Update `authorization_callback()` view to utilize SDK
  `get_explaination_of_benefit_data()` method in views.py

* Update server/src/data/Database.py for SDK usage.

* Updade server/src/utils/user_util.py for SDK usage.

* Remove files that the SDK usage has replaced:
   server/src/entities/Settings.py, server/src/entities/__init__.py,
   server/src/utils/bb2_util.py,
   server/src/utils/generatePKCE.py

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* Are there any unhandled and/or untested edge cases you can think of?
* Does this make any backwards-incompatible changes that might break end user clients?
* Can you find any bugs if you run the code locally and test it manually?
* Naming in general? Do the namings of variables, methods, classes, and other items make sense? Are they too verbose, or not verbose enough? Any redundancies? Are the comments descriptive enough?
* Are audit logging items properly handled? Is sensitive information either not included or hashed?

* *What/how to review:*

### How to test?

1. Checkout the [main](https://github.com/CMSgov/cms-bb2-python-sdk) branch of the `cms-bb2-python-sdk` repository.

2. Follow the package build instructions in the [README-sdk-dev.md](https://github.com/CMSgov/cms-bb2-python-sdk/blob/main/README-sdk-dev.md) to build a wheel type package file. 

3. Checkout the [dtisza1/BB2-1152_update_sample_app_to_use_SDK](https://github.com/CMSgov/bluebutton-sample-client-python-react/pull/15) PR branch in the `bluebutton-sample-client-python-react` repository. That is this PR's branch to be tested.

3. Copy the `cms_bluebutton-0.1.0-py3-none-any.whl` file in to the `server/` directory.

4. Remove the build for the server component and start up the containers. This will install the SDK via the Dockerfile.

  ```
  $ docker-compose down
  $ docker rmi bluebutton-sample-client-python-react_server
  $ docker-compose up -d
  $ docker-compose logs -f
    ```

5. Test the sample client at http://localhost:3000

### CODE REVIEW

**Comment by oragame** [comment]
tried to get through a test, I think i followed it correctly but will try again tomorrow I think. I am getting:
```
server_1  | ModuleNotFoundError: No module named 'src.configs.config'
bluebutton-sample-client-python-react_server_1 exited with code 1
```
I am able to get to the front end, so that is working well for me 👍

**Review by JFU-GIT — APPROVED** [review]
Tested with a wheel generated locally from SDK python repo, the end to end scenario works as expected, just some 2cents: 

After SDK is swapped in, many legacy code is by passed (no longer needed), may be it's good to do a clean up trimming off legacy code, such that a very concise SDK client code remains there, which serve the purpose of show case the SDK making app development easy and simple, may be only a few lines of code, and a BB2 app can be up and running.

**Comment by dtisza1** [comment]
> Tested with a wheel generated locally from SDK python repo, the end to end scenario works as expected, just some 2cents:
> 
> After SDK is swapped in, many legacy code is by passed (no longer needed), may be it's good to do a clean up trimming off legacy code, such that a very concise SDK client code remains there, which serve the purpose of show case the SDK making app development easy and simple, may be only a few lines of code, and a BB2 app can be up and running.

@JFU-GIT TY for reviewing and testing. Happy to hear it works as expected. 

That sounds great for cleaning up and swapping in the SDK code to this repo. As part of this PR I cleaned up legacy code, but more cleanup and docs could be updated too. We can leave this PR un-merged until a later date when the SDK is ready/published.

**Comment by dtisza1** [comment]
This is ready for review and testing.

**Comment by dtisza1** [comment]
Closing this draft. The work is covered in this PR:  https://github.com/CMSgov/bluebutton-sample-client-python-react/pull/26

**Pull request closed without merging**
